syntax on
set number
set mouse=a
set numberwidth=1
set relativenumber
set encoding=utf8
set laststatus=2
set noshowmode
set clipboard=unnamedplus
set guicursor=n-v-c-i:block
" searching
set hlsearch
set incsearch
set ignorecase
set smartcase
" tabs size
set expandtab
set shiftwidth=2
set tabstop=2
